---
- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: Copy H5BP configuration files
  copy:
    src: '{{ item }}'
    dest: '{{ nginx_root_path }}/'
  with_items:
    - sites-available
    - includes
    - snippets
    - mime.types
    - nginx.conf

- name: Create webroot directories
  file:
    name: "{{ nginx_web_root }}/{{ domain }}/public_html"
    state: directory
    owner: www-data

- name: Create index pages
  template:
    src: index.html.j2
    dest: "{{ nginx_web_root }}/{{ domain }}/public_html/index.html"
    owner: www-data

- name: Create virtual hosts files from template
  template:
    src: sites-available.conf.j2
    dest: "{{ nginx_sites_available }}/{{ domain }}.conf"
  notify: reload nginx

- name: Symlink enabled sites
  file:
    src: '{{ nginx_root_path }}/sites-available/{{ domain }}.conf'
    name: '{{ nginx_root_path }}/sites-enabled/{{ domain }}.conf'
    state: link
  notify: restart nginx
